<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**\**\*.xaml.cs" />
    <Compile Remove="AssemblyInfo.cs" />
    <Compile Remove="HelixModule\**\*.cs" />
    <None Remove="**\**\*.xaml" />
    <AvaloniaXaml Remove="**\**\*.xaml" />
    <Page Remove="**\**\*.xaml" />
    <ApplicationDefinition Remove="**\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModelingToolkit.Formats\ModelingToolkit.Core\ModelingToolkit.Core\ModelingToolkit.Core.csproj" />
    <ProjectReference Include="..\ModelingToolkit.Formats\ModelingToolkit.Formats\ModelingToolkit.Formats.csproj" />
  </ItemGroup>

</Project>
